#!/bin/bash
python3 -m pip uninstall refman -y && \   # Uninstall old versions
    pip install -r requirements.txt && \  # Install dependencies
    pytest && \                           # Run tests
    python3 setup.py install --user       # Install new version if tests succeed
